# System-wide package list. Anything already installed via a `programs.*`
# or `services.*` module (e.g. nekoray, docker) is intentionally left out
# here to avoid duplicate declarations.

{ config, lib, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    vim
    wget
    curl
    zellij
    waybar
    tree
    gvfs
    udisks2
    p7zip
    exfatprogs
    unzip
    pavucontrol
    bluez
    bluez-tools
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
    xfce.thunar
    xfce.thunar-archive-plugin
    xfce.thunar-volman
    xfce.tumbler
    wlr-randr
    wlogout
    wleave
    alacritty
    xdg-utils
    wl-clipboard
    swayidle
    swaylock
    swww
    imagemagick
    gnome-themes-extra
    adwaita-icon-theme
    adwaita-qt
    fuzzel
    glib
    gtk3
    cairo
    pango
    fontconfig
    freetype
    libglvnd
    sddm-astronaut
    mako
    networkmanagerapplet
    gnome-control-center
    bottom
    wallust
    openssh
    vlc
    ffmpeg
    mpv
    ripgrep
    grim
    slurp
    gnome-calendar
    gnome-clocks
    gnome-characters
    gnome-system-monitor
    gnome-calculator
    gnome-font-viewer
    baobab
    snapshot
    wdisplays
    phinger-cursors
    nordzy-cursor-theme
    mysql-client
    dnsmasq
    iw
    hostapd
    haveged
    rustup
    gcc
    pkg-config
    openssl
    nodejs_22
    pnpm
    insomnia
    file-roller
    kdePackages.qtmultimedia
  ];
}
