# Generated by ‘nixos-generate-config’, then hand-edited.
# Please make changes here (or better, in the topic modules under
# ./modules/) rather than only in a running system, so they survive
# reinstalls.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  # boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  # boot.kernelModules = [ "kvm-amd" ];

  # NOTE: previously this graphics block existed (commented out) for an
  # AMD GPU. It's replaced below with the enable flag needed for the
  # nvidia stack to have a working OpenGL/Vulkan userspace.
  hardware.graphics.enable = true;

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    # Use the "proprietary" driver (most common)
    modesetting.enable = true;

    # Power management (important for laptops!)
    powerManagement = {
      enable = true;
      # Fine-grained power management (newer GPUs)
      finegrained = false;
    };

    # Enable NVIDIA settings app
    nvidiaSettings = true;

    # Open kernel module (if you want open source components)
    open = true; # For newer GPUs (RTX 20 series and up)
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
        ReconnectAttempts = 7;
        ReconnectIntervals = "1, 2, 4, 8, 16, 32, 64";
      };
    };
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 8192;
    }
  ];

  # NOTE: add fsType (e.g. "ext4", "btrfs") here if you know it — it's
  # optional but makes mounting behavior explicit rather than guessed.
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXROOT";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXBOOT";
    fsType = "vfat";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
