# Generated by 'nixos-generate-config'.
#
# This file is currently SHARED by both hosts, which only works because both
# machines label their root and boot partitions NIXROOT/NIXBOOT and take the
# same initrd modules. To split it properly, run
#
#   nixos-generate-config --show-hardware-config > hosts/<host>/hardware-configuration.nix
#
# on each machine and import that from the host instead of this file.
#
# Keep this a pure hardware scan so it stays regenerable. Hand-written policy
# that used to live here has moved:
#   hardware.bluetooth   -> modules/nixos/hardware/bluetooth.nix
#   boot.kernelPackages  -> modules/nixos/core/boot.nix
#   swapDevices          -> hosts/<host>/default.nix
{ lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXROOT";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXBOOT";
    fsType = "vfat";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
