# Keeps the SDDM greeter in step with the current wallpaper, using the same
# wallust the rest of the session is themed with.
#
# The awkward constraint this package exists to work around: SDDM runs as the
# `sddm` system user *before* anyone logs in, so it can read neither $HOME nor
# anything wallust normally writes there, and the theme it renders lives
# read-only in the nix store. The escape hatch is SDDM's own override
# mechanism -- it reads `<theme>.conf` and then `<theme>.conf.user` on top --
# so ../sddm-astronaut-themed.nix points that second file at `stateDir` below
# and this package owns what gets written there.
#
# Everything a fresh machine needs is still baked into the theme package's
# base conf, so the greeter is correct before this has ever run; what lands in
# stateDir is only ever an override on top of that.
{
  lib,
  runCommand,
  writeText,
  writeShellScriptBin,

  # Single source of truth for the mutable theme directory. The NixOS module
  # creates it, the theme package symlinks its .conf.user into it and the
  # script below writes it, so all three read the path from here rather than
  # repeating a string. Owned by the desktop user and world-readable: the
  # desktop user writes it on every wallpaper change, `sddm` only reads it.
  stateDir ? "/var/lib/sddm-theme",

  # Matches the greeter's own panels. Both are 1080p; 2560 leaves headroom for
  # a 1440p panel without re-exporting.
  backgroundWidth ? 2560,

  # Pinned rather than following darkman: the greeter is what you see at boot,
  # before any session (and so any mode) exists, and darkman starts sessions
  # dark anyway. Changing this to a light palette is a one-word edit.
  palette ? "dark16",
}:

let
  colorsFile = "${stateDir}/colors.conf";
  backgroundFile = "${stateDir}/bg.jpg";

  # wallust writes here and the script renames it into place, so a login that
  # happens mid-write can never read a half-written config.
  colorsTmp = "${colorsFile}.tmp";

  # The four roles the greeter's ~30 color keys are built from. color4 is the
  # accent everywhere else in this repo too -- see the mako and fuzzel
  # templates in ../../modules/home/saeedp11/wallust.nix -- so the greeter
  # picks the same accent out of a wallpaper that the notifications and the
  # launcher do.
  #
  # color0 is the "one step above the background" surface, used for the
  # hovered row of the session menu. Measured over the whole wallpaper
  # library (132 images), it keeps the foreground between 5.1:1 and 19.9:1 on
  # that row -- never below WCAG AA -- and comes back exactly equal to the
  # background for 3 of them, where the only cost is that the hover tint
  # stops being visible. The accent is the obvious alternative and is worse:
  # it is always distinct from the background, but it puts the foreground at
  # 2.5:1 to 4.3:1 on that row for *every* wallpaper. Losing a hover tint on
  # 2% of the library beats permanently marginal text.
  template = writeText "sddm-colors.conf" ''
    # Generated by sddm-sync-theme from the current wallpaper. Do not edit:
    # rewritten on every wallpaper change. The defaults this overrides are in
    # the theme package's own conf, which is what the greeter falls back to.
    [General]
    Background="${backgroundFile}"

    HeaderTextColor="{{foreground}}"
    DateTextColor="{{foreground}}"
    TimeTextColor="{{foreground}}"

    FormBackgroundColor="{{background}}"
    BackgroundColor="{{background}}"
    DimBackgroundColor="{{background}}"

    LoginFieldBackgroundColor="{{foreground}}"
    PasswordFieldBackgroundColor="{{foreground}}"
    LoginFieldTextColor="{{foreground}}"
    PasswordFieldTextColor="{{foreground}}"
    UserIconColor="{{foreground}}"
    PasswordIconColor="{{foreground}}"

    PlaceholderTextColor="{{color8}}"
    WarningColor="{{color4}}"

    LoginButtonBackgroundColor="{{color4}}"
    LoginButtonTextColor="{{background}}"
    SystemButtonsIconsColor="{{foreground}}"
    SessionButtonTextColor="{{foreground}}"
    VirtualKeyboardButtonTextColor="{{foreground}}"

    DropdownBackgroundColor="{{background}}"
    DropdownTextColor="{{foreground}}"
    DropdownSelectedBackgroundColor="{{color0}}"

    HighlightBackgroundColor="{{color4}}"
    HighlightTextColor="{{background}}"
    HighlightBorderColor="{{color4}}"

    HoverUserIconColor="{{color4}}"
    HoverPasswordIconColor="{{color4}}"
    HoverSystemButtonsIconsColor="{{color4}}"
    HoverSessionButtonTextColor="{{color4}}"
    HoverVirtualKeyboardButtonTextColor="{{color4}}"
  '';

  # A config directory of our own rather than the user's ~/.config/wallust.
  # That file is tracked in the dotconfig repo and drives the live session, so
  # adding a [templates] entry to it would mean this repo editing a file it
  # does not own -- and it would tie the greeter to whatever palette the
  # session happens to be using.
  configDir = runCommand "sddm-wallust-config" { } ''
    mkdir -p $out/templates
    cp ${template} $out/templates/sddm-colors.conf
    cat > $out/wallust.toml <<EOF
    backend = "resized"
    color_space = "lab"
    palette = "${palette}"
    check_contrast = true

    [templates]
    sddm = { template = "sddm-colors.conf", target = "${colorsTmp}" }
    EOF
  '';

  syncScript = writeShellScriptBin "sddm-sync-theme" ''
    #!/usr/bin/env bash
    # Point the login screen at the wallpaper the session is using, and
    # repaint it in that wallpaper's colors.
    #
    # Runs as the desktop user (stateDir is owned by them), never as root, and
    # is deliberately best-effort: nothing here is worth failing a wallpaper
    # change over, so every step warns and continues.
    set -uo pipefail

    if [ $# -lt 1 ] || [ ! -f "$1" ]; then
        echo "Usage: sddm-sync-theme <path-to-image>" >&2
        exit 1
    fi
    WALLPAPER="$1"

    # The NixOS module owns this directory. If SDDM is not enabled on this
    # host it will not exist, which is not an error -- there is just no
    # greeter to sync.
    if [ ! -d "${stateDir}" ]; then
        exit 0
    fi

    # `[0]` takes the first frame so animated GIFs work, matching what
    # wallpaper-thumbs does. Written to a temp file and renamed because the
    # greeter may read this at any moment.
    bg_tmp="${backgroundFile}.tmp.$$"
    if magick "$WALLPAPER[0]" -auto-orient -resize ${toString backgroundWidth}x \
            -strip -sampling-factor 4:2:0 -quality 92 -interlace Plane \
            "JPEG:$bg_tmp" 2>/dev/null; then
        chmod 0644 "$bg_tmp" && mv -f -- "$bg_tmp" "${backgroundFile}"
    else
        rm -f -- "$bg_tmp"
        echo "sddm-sync-theme: could not render background from: $WALLPAPER" >&2
    fi

    # -s and -n keep this out of the session's way: no terminal sequences and
    # no cache writes, so the palette the *session* is using (set by the
    # wallust run in set-wallpaper) is untouched by this second run.
    # -k asks wallust to keep the colors readable against the background it
    # picked, which is what makes an arbitrary wallpaper still give a legible
    # login form.
    if wallust run "$WALLPAPER" -d ${configDir} -p ${palette} -k -s -n -q 2>/dev/null \
            && [ -f "${colorsTmp}" ]; then
        chmod 0644 "${colorsTmp}" && mv -f -- "${colorsTmp}" "${colorsFile}"
    else
        rm -f -- "${colorsTmp}"
        echo "sddm-sync-theme: wallust failed on: $WALLPAPER" >&2
    fi
  '';
in
syncScript.overrideAttrs (old: {
  passthru = (old.passthru or { }) // {
    inherit
      stateDir
      colorsFile
      backgroundFile
      configDir
      ;
  };
})
