# GTK3 menu styling.
#
# WHY THIS FILE EXISTS AT ALL. It restyles every GTK3 menu in the session
# at once, with nothing done per app. It was written when waybar drew the
# tray: waybar builds each tray menu itself as a GtkMenu, out of what the app
# exports over com.canonical.dbusmenu, so nekoray's, blueman's and
# nm-applet's menus were all GTK3 menus in waybar's process. The tray is now
# Quickshell's (./quickshell.nix), a Qt process, so what this file reliably
# reaches is GTK3 applications' own menus.
#
# WHY THE COLORS COME FROM THE THEME AND NOT FROM WALLUST. Every other
# color in this session is generated by wallust from the wallpaper, so the
# obvious thing would be a wallust template feeding an @import here, the
# way ./wallust.nix does for the shell. It does not work: GTK3 reads
# ~/.config/gtk-3.0/gtk.css exactly once, when a process starts, and never
# again. Measured on GTK 3.24.49 with a live menu on screen -- rewriting
# gtk.css, and rewriting a file it @imports, both left a running process's
# menus unchanged after five seconds. A wallust palette would therefore
# only reach a menu in an application started after the change, and would
# be wrong in every running one until it restarts.
#
# Adwaita's named colors do not have that problem. @theme_bg_color and
# @theme_fg_color are resolved against whichever theme provider is current
# at the time a style is computed, so when the darkman 10-gtk hook
# (./darkman-hooks/*/10-gtk.sh) flips gtk-application-prefer-dark-theme,
# menus repaint live along with everything else -- measured in the same
# process, menu background #565656 in dark mode and #d3d3d3 in light. That
# is the property worth having here, so the file is written in terms of
# those two colors and derives its highlight and separators as alphas of
# the foreground rather than picking any color of its own.
#
# The file lands at GTK_STYLE_PROVIDER_PRIORITY_USER, above the theme.
#
# GTK4 gets nothing: its menus are popovers, a different widget tree.
{ ... }:

{
  # A single file, not the directory: settings.ini sits beside it and is
  # rewritten at runtime by the darkman hook, so it cannot become a
  # read-only store symlink (./default.nix spells this out).
  xdg.configFile."gtk-3.0/gtk.css".source = ./gtk/gtk3.css;
}
