# GTK3 menu styling.
#
# WHY THIS FILE EXISTS AT ALL. Every tray menu in this session is a GTK3
# menu, including the ones belonging to apps that are not GTK: waybar's
# tray is a StatusNotifierItem host, and it links libdbusmenu-gtk3 and
# builds the menu itself out of what the app exports over
# com.canonical.dbusmenu. So nekoray's Qt menu, blueman's and nm-applet's
# are all GtkMenu widgets living in waybar's process, and restyling GTK3
# menus is what restyles all three at once. Nothing needs to be done per
# app, and nothing here reaches into waybar/style.css, which the dotconfig
# repo owns (see ./default.nix on why that file stays there).
#
# WHY THE COLORS COME FROM THE THEME AND NOT FROM WALLUST. Every other
# color in this session is generated by wallust from the wallpaper, so the
# obvious thing would be a wallust template feeding an @import here, the
# way ./wallust.nix does for fuzzel. It does not work: GTK3 reads
# ~/.config/gtk-3.0/gtk.css exactly once, when a process starts, and never
# again. Measured on GTK 3.24.49 with a live menu on screen -- rewriting
# gtk.css, and rewriting a file it @imports, both left a running process's
# menus unchanged after five seconds. A wallust palette would therefore
# only reach a tray menu on the next waybar restart, and would be wrong
# after every wallpaper change until then.
#
# Adwaita's named colors do not have that problem. @theme_bg_color and
# @theme_fg_color are resolved against whichever theme provider is current
# at the time a style is computed, so when the darkman 10-gtk hook
# (./darkman-hooks/*/10-gtk.sh) flips gtk-application-prefer-dark-theme,
# menus repaint live along with everything else -- measured in the same
# process, menu background #565656 in dark mode and #d3d3d3 in light. That
# is the property worth having here, so the file is written in terms of
# those two colors and derives its highlight and separators as alphas of
# the foreground rather than picking any color of its own.
#
# The file lands at GTK_STYLE_PROVIDER_PRIORITY_USER, above the theme, and
# waybar's own style.css defines no menu rules, so nothing here competes
# with the bar.
#
# GTK4 gets nothing: its menus are popovers, a different widget tree, and
# no tray menu is drawn by GTK4.
{ ... }:

{
  # A single file, not the directory: settings.ini sits beside it and is
  # rewritten at runtime by the darkman hook, so it cannot become a
  # read-only store symlink (./default.nix spells this out).
  xdg.configFile."gtk-3.0/gtk.css".source = ./gtk/gtk3.css;
}
