# mako's visual configuration.
#
# The file only, not the service: mako is launched by niri's
# spawn-at-startup (see ~/.config/niri/config.kdl in the dotconfig repo),
# and enabling Home Manager's `services.mako` would add a second, competing
# systemd user unit. The daemon binary and the sound-on-notify watcher come
# from modules/nixos/desktop/notifications.nix.
#
# ~/.config/mako/wallust-colors is NOT managed here -- wallust regenerates
# it on every wallpaper change and dark/light toggle.
{ ... }:

{
  xdg.configFile."mako/config".text = ''
    anchor=top-right
    margin=10
    padding=12
    width=350
    height=110
    border-size=2
    border-radius=10
    font=Ubuntu 11
    default-timeout=6000
    max-visible=5
    group-by=app-name
    icons=1
    max-icon-size=48

    # Colors regenerated by wallust on every wallpaper change and on every
    # dark/light toggle (see dark-mode.d/light-mode.d's 15-wallust.sh and
    # 20-reload-bar.sh). Falls back to these if wallust hasn't run yet.
    background-color=#282828
    text-color=#ebdbb2
    border-color=#458588
    include=~/.config/mako/wallust-colors

    [urgency=low]
    border-color=#928374

    [urgency=critical]
    border-color=#cc241d
    default-timeout=0
  '';
}
